### ISSUE TITLE
1.3 Crash/Possible Save Corruption

### ISSUE THREAD

**Issue by jestesared** [scalda/FoolCraft#329]
## SUGGESTION/HELP
- [ ] I would like to propose an additional mod, config change, custom recipe, etc.
- [ x] I am requesting help with installing or running the pack

## Issue Description
After updating to 1.3, the game prompted me to make a backup, warning something about a level.dat file, so I did. After reloading the launcher and trying to start my world, it starts then MC completely crashes. It gives a message of "The game crashed whilst exception ticking world
Error: java.lang.NoClassDefFoundError: net/minecraft/world/World$2"
Then it shows the button for viewing the crash report, but it wont pull it up or anything. No idea what to do next...

## Additional Information
http://i.imgur.com/ohTqhRT.png
Like I said, the view crash report button is unresponsive.
Here also is the backup, just in case. https://drive.google.com/open?id=0BxCH3cuWyjzgeFdyMlNKb0lXa00

**Comment by scalda** [comment]
1.3.1 is under review, please once available can you check again and let me know how it goes. thanks in advance

**Comment by scalda** [comment]
Hi, i have found the bug that was causing the world errors and 1.3.2 is uploading now and under review. please BACKUP your world first before updating.

Thanks in advance

Scalda
